const bookmarkPreset = {};

bookmarkPreset.get = () => {
  return [
    {
      name: { show: false, text: "Cool stuff" },
      items: [
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "DEV" },
              image: {
                url: "https://brandlogos.net/wp-content/uploads/2025/02/deepseek_logo_icon-logo_brandlogos.net_s5bgc.png",
              },
              icon: { name: "", prefix: "", label: "" },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Devdocs", size: 7 },
          },
          url: "https://chat.deepseek.com/",
          accent: {
            by: "custom",
            hsl: { h: 230, s: 99, l: 65 },
            rgb: { r: 77, g: 107, b: 254 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "video",
            opacity: 15,
            image: { url: "" },
            video: { url: "https://www.ubiq.ad/video.webm" },
          },
          timestamp: 1546453101749,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "R" },
              image: {
                url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/500px-Google_Calendar_icon_%282020%29.svg.png",
              },
              icon: {
                name: "calendar-alt",
                prefix: "fas",
                label: "Alternate Calendar",
              },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Reddit", size: 7 },
          },
          url: "https://calendar.google.com/",
          accent: {
            by: "custom",
            hsl: { h: 217, s: 89, l: 61 },
            rgb: { r: 66, g: 133, b: 244 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "video",
            opacity: 100,
            image: { url: "" },
            video: { url: "https://www.ubiq.ad/video.webm" },
          },
          timestamp: 1546453111491,
          border: 0,
          shape: { wide: true, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "icon",
              letter: { text: "GIT" },
              image: { url: "" },
              icon: { name: "github", prefix: "fab", label: "GitHub" },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Github", size: 7 },
          },
          url: "https://github.com/",
          accent: {
            by: "custom",
            hsl: { h: 0, s: 0, l: 100 },
            rgb: { r: 255, g: 255, b: 255 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453108926,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "icon",
              letter: { text: "AS" },
              image: { url: "" },
              icon: {
                name: "dice-d20",
                prefix: "fas",
                label: "Dice D20",
              },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "awesomeSheet", size: 7 },
          },
          url: "https://codi.link",
          accent: {
            by: "custom",
            hsl: { h: 218, s: 49, l: 42 },
            rgb: { r: 55, g: 93, b: 160 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453104010,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "AZ" },
              image: {
                url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Google_Keep_icon_%282015-2020%29.svg/960px-Google_Keep_icon_%282015-2020%29.svg.png",
              },
              icon: {
                name: "sticky-note",
                prefix: "fas",
                label: "Sticky Note",
              },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Amazon", size: 7 },
          },
          url: "https://keep.google.com/",
          accent: {
            by: "custom",
            hsl: { h: 45, s: 100, l: 50 },
            rgb: { r: 255, g: 191, b: 0 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453107633,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "N" },
              image: {
                url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png",
              },
              icon: { name: "film", prefix: "fas", label: "chat" },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Netflix", size: 7 },
          },
          url: "https://chatgpt.com/",
          accent: {
            by: "custom",
            hsl: { h: 164, s: 25, l: 57 },
            rgb: { r: 117, g: 172, b: 157 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453104460,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "DR" },
              image: {
                url: "https://cdn-icons-png.flaticon.com/512/5968/5968517.png",
              },
              icon: { name: "file", prefix: "fas", label: "File" },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Drive", size: 7 },
          },
          url: "https://docs.google.com/",
          accent: {
            by: "custom",
            hsl: { h: 220, s: 100, l: 70 },
            rgb: { r: 102, g: 153, b: 255 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453111953,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          display: {
            direction: "vertical",
            order: "visual-name",
            alignment: "center-center",
            gutter: 20,
            rotate: 0,
            translate: { x: 0, y: 0 },
            visual: {
              show: true,
              type: "image",
              letter: { text: "GM" },
              image: {
                url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gmail_icon_%282020%29.svg/1280px-Gmail_icon_%282020%29.svg.png",
              },
              icon: {
                name: "envelope",
                prefix: "fas",
                label: "Envelope",
              },
              shadow: { size: 0 },
              size: 30,
            },
            name: { show: false, text: "Gmail", size: 7 },
          },
          url: "https://mail.google.com/",
          accent: {
            by: "custom",
            hsl: { h: 0, s: 100, l: 50 },
            rgb: { r: 255, g: 0, b: 0 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          timestamp: 1546453110265,
          border: 0,
          shape: { wide: false, tall: false },
        },
        {
          url: "https://gemini.google.com/app",
          display: {
            alignment: "center-center",
            direction: "vertical",
            order: "visual-name",
            rotate: 0,
            translate: { x: 0, y: 0 },
            gutter: 25,
            name: { show: false, text: "", size: 7 },
            visual: {
              show: true,
              type: "image",
              size: 25,
              letter: { text: "" },
              icon: { name: "", prefix: "", label: "" },
              image: {
                url: "https://static.vecteezy.com/system/resources/previews/055/687/065/non_2x/gemini-google-icon-symbol-logo-free-png.png",
              },
              shadow: { size: 0 },
            },
          },
          accent: {
            by: "custom",
            hsl: { h: 264, s: 84, l: 29 },
            rgb: { r: 62, g: 12, b: 135 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          border: 0,
          shape: { wide: false, tall: false },
          timestamp: 1736808004646,
        },
        {
          url: "https://youtube.com",
          display: {
            alignment: "center-center",
            direction: "vertical",
            order: "visual-name",
            rotate: 0,
            translate: { x: 0, y: 0 },
            gutter: 25,
            name: { show: false, text: "", size: 7 },
            visual: {
              show: true,
              type: "icon",
              size: 25,
              letter: { text: "" },
              icon: {
                name: "youtube",
                prefix: "fab",
                label: "YouTube",
              },
              image: { url: "" },
              shadow: { size: 0 },
            },
          },
          accent: {
            by: "custom",
            hsl: { h: 0, s: 75, l: 44 },
            rgb: { r: 196, g: 28, b: 28 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          border: 0,
          shape: { wide: false, tall: false },
          timestamp: 1702305097613,
        },
        {
          url: "https://www.instagram.com/",
          display: {
            alignment: "center-center",
            direction: "vertical",
            order: "visual-name",
            rotate: 0,
            translate: { x: 0, y: 0 },
            gutter: 25,
            name: { show: false, text: "INSTAGA", size: 7 },
            visual: {
              show: true,
              type: "icon",
              size: 25,
              letter: { text: "" },
              icon: {
                name: "instagram",
                prefix: "fab",
                label: "Instagram",
              },
              image: { url: "" },
              shadow: { size: 0 },
            },
          },
          accent: {
            by: "custom",
            hsl: { h: 281, s: 100, l: 43 },
            rgb: { r: 150, g: 0, b: 219 },
          },
          color: {
            by: "theme",
            hsl: { h: 0, s: 0, l: 0 },
            rgb: { r: 0, g: 0, b: 0 },
            opacity: 100,
          },
          background: {
            show: false,
            type: "image",
            opacity: 100,
            image: { url: "" },
            video: { url: "" },
          },
          border: 0,
          shape: { wide: false, tall: false },
          timestamp: 1705598238608,
        },
      ],
      toolbar: {
        openAll: { show: false },
        collapse: { show: false },
      },
      collapse: false,
    },
  ];
};

export { bookmarkPreset };
